# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-app-service
# spec:
#   type: NodePort
#   ports:
#     - port: 80          
#       targetPort: 5001  
#       nodePort: 30001    
#     app: flask-app

apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - port: 80         # ClusterIP (inside k8s)
      targetPort: 5001 # Container port
      nodePort: 30001  # External access on each node
