# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: flask-app-deployment
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: flask-app
#   template:
#     metadata:
#       labels:
#         app: flask-app
#     spec:
#       containers:
#       - name: flask-app
#         image: my-flask-app:latest   
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 5001

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: my-flask-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
