name:demo2

on:
  push:
    branches: [ "main1" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production2
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch origin
          git checkout -B production2
          git reset --hard origin/main1
          git push origin production2 --force
